### ISSUE TITLE
Biom'es o' Plenty World Type

### ISSUE THREAD

**Issue by Ado-line** [fraenkelc/amidst-forge#11]
Hi, I can't find much documentation for this mod. I was just wondering how to set the generation in amidst to the biomes o plenty world type (BIOMESOP in MC-1.12.2)? Otherwise none of those biomes appear
Thanks in advance!

**Comment by fraenkelc** [comment]
For mods that just add biomes to the biome generation like traverse you can use the launch amidst button in the options menu and generate maps for specific seeds in amidst. For mods like BoP or RTG you'll need to create the world with the correct seed in minecraft, then launch Amidst using the "Amidst Overworld" button in the options window. There's no way to select the BoP world type in Amidst and just view worlds from there.

**Comment by Ado-line** [comment]
![image](https://user-images.githubusercontent.com/11416064/60060585-92a0d300-96ae-11e9-9827-ede70ef068fa.png)
So I generate a new BOP world
![image](https://user-images.githubusercontent.com/11416064/60060602-a9dfc080-96ae-11e9-8696-f2b9205dc371.png)
then I open Amidst Overworld
![image](https://user-images.githubusercontent.com/11416064/60060619-bb28cd00-96ae-11e9-9f86-1fe79075f7e0.png)
Then what?

**Comment by fraenkelc** [comment]
Use “New from random seed”  (in the file menu) to open the map.

**Comment by Ado-line** [comment]
Oh I see, ok thank you!
