### ISSUE TITLE
Amidst asks to update on every load

### ISSUE THREAD

**Issue by Igfig** [fraenkelc/amidst-forge#12]
Every time I open Amidst via this mod, it says there's an update out for Amidst and asks me if I want to update. (From v4.3-beta2 to v4.3.) I can click yes and download a new version just fine... but I don't see any way to make it use the new version. Replacing the Amidst jar in the mods/1.12.2 folder does nothing; the mod just redownloads v4.3-beta2 and ignores the replacement.

I can only imagine the version to download must be hardcoded somehow? Or it comes from some external source that hasn't been updated yet?

Whatever it is, it's quite annoying. Please either update the hardcoded version number, or make it possible for us to update Amidst manually. (Or, if it's already possible to update it manually, please explain how somewhere in the documentation.)

Thanks!

**Comment by fraenkelc** [comment]
amidst forge ships with its own modified version of forge which can't be updated manually. Sadly I haven't had much luck in getting any patches into amidst to remove this bundling requirement.

I'll look into disabling the update check on my fork and pushing a new release.

**Comment by fraenkelc** [comment]
I've uploaded a version without the update check notice. If you get the notice after updating please close minecraft and amidst and delete the `mods\1.12.2\amidst-4.3-beta2-all.jar` file and try again.

**Comment by Igfig** [comment]
Not getting the update message any more. Thank you!

**Comment by Doublehelix13** [comment]
I have the latest version for 1.12.2 and I am still getting the update prompt.
