### ISSUE TITLE
Unable to load savegame

### ISSUE THREAD

**Issue by pinheadtf2** [fraenkelc/amidst-forge#14]
![error](https://user-images.githubusercontent.com/42384617/71782214-44458880-2f9d-11ea-9a09-2c760a71c7dc.PNG)

The load from seed works fine, but load from save spits that error. I am using MultiMC which could be a cause, but I did this in normal launcher too, same error. 

[Text Version](https://pastebin.com/w7Qn2Qwg)

**Comment by fraenkelc** [comment]
Thanks for your report. Load from save is (currently) not supported. Please use the seed functionality for now. 
I've kept my modifications to the amidst source to a minimum in hopes of getting a proper integration merged into upstream. As a result there's a number of features that either don't work or even throw errors. I might make a pass in the future where I remove such non working functionality (just like the load from save one), but I haven't decided on that yet.
