### ISSUE TITLE
Launches but doesn't show map. No biomes O' Plenty support?

### ISSUE THREAD

**Issue by BinaryVigilante** [fraenkelc/amidst-forge#15]
Hello!

I just stumpled upon your mod, really cool! I really need to find a specific biome in my world, and I haven't been able to find anything else that work. And from my understanding, this mod should support modded biomes correct?

Well, I have my world with Biomes O' Plenty, but when I launch it, it's just blank, and when generating a new random seed, Biomes O' Plenty world-type isn't on the list.

The following image is me using the "Amidst Overworld" button.
![image](https://user-images.githubusercontent.com/24778415/73787338-65b3b300-479b-11ea-94d6-913f9e4f247c.png)

And the following image shows the world-types available:
![image](https://user-images.githubusercontent.com/24778415/73787423-8e3bad00-479b-11ea-9150-cb35be84892a.png)

Am I just completely missing something or is Biomes O' Plenty not supported?

**Comment by fraenkelc** [comment]
This mod does not extend the world type selection to include modded world types so creating a world from inside amidest won't work. Creating the world from inside minecraft and using "Amidst Overworld" should work on the other hand.
What versions of forge, amidst for forge and biomes o plenty are you using?

**Comment by BinaryVigilante** [comment]
Here are the versions:
Minecraft: 1.12.2
Forge: 2820
BoP: 7.0.1.2441
Amidst for Forge: 0.6.2

**Comment by BinaryVigilante** [comment]
Also a thing to note when I'm just in the main menu and launched Amidst and click on "Open save game" nothing happens, and also it says this on the top of the program:
![image](https://user-images.githubusercontent.com/24778415/73796772-6c97f100-47ae-11ea-894d-539b47ce6869.png)

**Comment by BinaryVigilante** [comment]
Alright, update!
After I found a video, where he showed how he used the mod, I finally got it to work. Let me describe what I did:

I clicked on "Amidst Overworld"
![image](https://user-images.githubusercontent.com/24778415/73870101-bda9f280-484b-11ea-8bab-18d3ddf3d0fb.png)

Then, I clicked on File -> New from seed
![image](https://user-images.githubusercontent.com/24778415/73870152-d6b2a380-484b-11ea-82af-8509c66ca080.png)

Then I get this. Here I have to manually type in my world seed.
![image](https://user-images.githubusercontent.com/24778415/73870182-e631ec80-484b-11ea-84a9-c8115db8e8f9.png)

And then I select "Default" here:
![image](https://user-images.githubusercontent.com/24778415/73870208-f2b64500-484b-11ea-8ef2-fb213c177877.png)
This one is a little confusing because of Biomes O' Plenty not being in the menu, but just leave it at default and it will detect Biomes O' Plenty biomes.

Clearly shown here, as "redwood forest" isn't a vanila biome:
![image](https://user-images.githubusercontent.com/24778415/73870304-242f1080-484c-11ea-894d-b82201a1a3c2.png)

But yet still the "open save game" button doesn't work for me, which would be the nicest so I could see things in the actual world without it showing me a new one, also so I can see the player location and such. Idk why that part won't work..

**Comment by fraenkelc** [comment]
good to hear that Amidst Overworld is working for you. I agree that the integration right now has a number of deficits and contains quite a number of features that either do nothing (world type selection) or do not work at all (load from save, see also #14).
As it stands right now I'm trying to keep my fork of Amidst and  my changes to it to a minimum in hopes of getting them integrated in some fashion into master.

I'll take a look and try to improve documentation a bit and try to clarify how to use the Amidst Overworld function and mention some known features that don't work / are not implemented.
