### ISSUE TITLE
Amidst Stops Loading after a Short Time

### ISSUE THREAD

**Issue by Doublehelix13** [fraenkelc/amidst-forge#19]
After only a minute or so of use, the map stops loading and changes (highlighting biomes, removing the grid, showing slime chunks, etc.) stop being applied.  It happens so soon that Amidst is almost useless.  This is for 1.12.2-0.6.2.
![Screen Shot 2020-02-28 at 2 53 03 PM](https://user-images.githubusercontent.com/40927088/75586510-37439380-5a3a-11ea-8375-1f5fa3786be1.png)

**Comment by fraenkelc** [comment]
Judging from your post in #12 you probably updated amidst for forge from an older version. Please stop minecraft, delete the file "amidst-4.3-beta2-all.jar" inside the mods folder and try again.

**Comment by Doublehelix13** [comment]
There is no "amidst-4.3-beta2-all.jar" file in my mods folder.  I only have "amidst-forge-1.12.2-0.6.2.jar" in my mods folder.  I have tried deleting and reinstalling and both problems still occur.

**Comment by fraenkelc** [comment]
please also check the "mods\1.12.2\" for the amidst-4.3-beta2-all.jar

**Comment by Doublehelix13** [comment]
Where is that folder?  I've never seen that before.

**Comment by fraenkelc** [comment]
![image](https://user-images.githubusercontent.com/4005102/75623873-ffaa2800-5bae-11ea-8055-62c031bc8ad1.png)

**Comment by Doublehelix13** [comment]
I have located the "amidst-4.3-beta2-all.jar" file in the "mods\1.12.2" folder and deleted it.  However, each time I play the modpack, the file reappears.  The update prompt is gone and Amidst seems to work for a while, but after a few uses, it stops loading again.

**Comment by fraenkelc** [comment]
Deleting it once was enough, you do not need to delete it again while using this version of amidst for forge.
Now that we have an up to date version of amidst we can work on the update issue:
* Please posts your forge version
* Are you using a modpack? If so, what modpack and what version?
* If not, what mods that affect biome and world generation are you using?
* What world type did you use when generating your world?
* Does your latest log contain any exceptions related to Amidst ? If so please post them to pastebin or a gist and post the link to it here.

**Comment by fraenkelc** [comment]
Closing this as there hasn't been any activity for a month.
