### ISSUE TITLE
Forge 1.12.2 (2613)  only generates a black screen with "unknown biome"

### ISSUE THREAD

**Issue by MLMII** [fraenkelc/amidst-forge#2]
Sorry to bother you, but in Forge 1.12.2 (2613), when I open Amidst and enter a seed manually all it generates is a black screen with "unknown". 

![screenshot_default_73451566](https://user-images.githubusercontent.com/19582002/35980347-b82cbc3e-0ca7-11e8-9715-2e0eef7d82e4.png)

**Comment by fraenkelc** [comment]
Thanks for the report, I was able to reproduce the problem. I've uploaded a new release that should fix the issue. It's currently going through the curse review process and should be available soon.
