### ISSUE TITLE
GeographiCraft Incompatiablity 

### ISSUE THREAD

**Issue by MLMII** [fraenkelc/amidst-forge#3]
I'm not sure if this is something that you're interested in or if its even something that is fixable but when I open Amidst from within the game it doesn't aknowledge the changes that GeographiCraft makes in the world's landmasses.   (The last update fixed my black screen issue, thanks.)

**Comment by fraenkelc** [comment]
I'll take a look at how GeographiCraft hooks the worldgen this weekend and see what I can do.

**Comment by fraenkelc** [comment]
The next version (0.4.0) will have some basic compatibility for mods like Geographicraft:
![minecraft next to amidst](https://i.imgur.com/9lKlg7x.png)
![amidst](https://i.imgur.com/7Spd2t9.png)

The map looks ok and matches up. The structure locations are messed up - I probably won't be improving on that part as I suspect I would have to mess quite a bit with amidst to get some progress on that.

**Comment by MLMII** [comment]
Thanks
