### ISSUE TITLE
"Open Terrain Generation"  causes a Black Screen.

### ISSUE THREAD

**Issue by MLMII** [fraenkelc/amidst-forge#4]
Here is the link for OTG if you wanted to take a look.

https://minecraft.curseforge.com/projects/open-terrain-generator?gameCategorySlug=mc-mods&projectID=265894

**Comment by fraenkelc** [comment]
Thanks for the report. I've looked at the issue and found the cause. I'll take a look during the week and decide what fix I'll implement for it.

**Comment by fraenkelc** [comment]
give 0.5.0 a try. I've added a fallback for cases when mods replace the BiomeProvider with their own (as is the case for OTG). This only works once you joined a singleplayer world using the Amidst overworld button.

**Comment by scottosx** [comment]
I am having the black screen problem with OTG Biome Bundle and Amidst for Forge 0.5.0 

Also with Traverse I have a recursive error window that spawn dozens of instances before I force quit. This is on a Mac btw. I can make a video of that if you need to see it.

**Comment by fraenkelc** [comment]
What exact mod and forge versions are you using?

**Comment by scottosx** [comment]
A very bare testing pack:
Forge 2627
Minecraft 1.12.2
Open Terrain Generation v5
Biome Bundle v6.1
JourneyMap 5.5.2
JEI 4.8.5.159
One Probe 1.4.19
Amidst for Forge 0.5.0

**Comment by scottosx** [comment]
I will do a lot more testing today because I am working on a mod showcase video.
A bare pack with only JourneyMap, JEI, One Probe, Amidst for Forge and Traverse 1.3.1 worked fine. So some other biome mod in combination is Traverse may be causing a problem.

**Comment by scottosx** [comment]
Ok, the mod that conflicts with Traverse and Amidst for Forge is Terra (Biomes and Stuff) https://www.curseforge.com/minecraft/mc-mods/terra-biomes-stuff

When those two are in combination with the test pack above. I get the recursive error window. I can't read what it says. It spawns dozens very fast.

**Comment by fraenkelc** [comment]
The fast error dialogs usually happen when amidst tries to deal with a biome that it doesn't know about. I'll take a look at what might cause this over the weekend. You might want to try joining a world and using the amidst overworld button, I suspect it will work.

**Comment by fraenkelc** [comment]
So, the issue for the popups was that both Traverse and Terra register Biomes with the name "Woodlands" and "Meadow" and my code was not able to deal with that. I should have a fix for that shortly. I'll have a look at the black map issue with biome bundle next.

**Comment by fraenkelc** [comment]
So, turns out I won't be able to fully support Open Terrain Generator. Amidst is limited to 256 biomes. OTG circumvents that limit using its  ReplaceToBiomeName feature.
@scottosx :If you find further problems please open a new issue.

**Comment by scottosx** [comment]
Thanks for your attention. I understand about OTG and its unusual system of biome numbering. Any further issues I find I will report. A mod showcase video will be done soon.

**Comment by fraenkelc** [comment]
Thanks. My work here only does the integration to forge though - the heavy lifting is all being done by [Amidst](https://github.com/toolbox4minecraft/amidst)

**Comment by Alaisx** [comment]
I am having the OTG black screen issue with Amidst 0.6.0 with the following mods installed:
OpenTerrainGenerator-1.12.2 - v6.jar
OTG-Skylands-1.12.2-v5.jar
amidst-forge-1.12.2-0.6.0.jar

Skylands is a preset for OTG that has ~60 biomes, so should be well below the 256 biome limit. I am launching a Skylands world and using Amidst Overworld, then choosing "New from random seed" and selecting the "default" world type (only vanilla world types are available - I assume this is normal?) After this, I get the black screen with "unknown" biomes. Also tried with the Flatlands preset. 

Edit: The first issue was apparently that the Biome IDs of the preset were above 256. However, setting them to below 256 (and avoiding vanilla assigned values) results in that continuous stream of blank error windows.
