### ISSUE TITLE
[Review] Video Showcase for Amidst for Forge

### ISSUE THREAD

**Issue by scottosx** [fraenkelc/amidst-forge#5]
Here is a showcase for your mod on YouTube. https://youtu.be/wiKuL6f_aWg

Please tell me if I have gotten anything wrong and how you like it.

**Comment by fraenkelc** [comment]
Thanks, I'll take a look this evening.

**Comment by fraenkelc** [comment]
Thanks for doing the showcase, it looks great. I think you touched on all the relevant points, even the special handling for traverse.

**Comment by fraenkelc** [comment]
Clicking on the map icons does work on my machine. could you try it the issue also occurs with the plain standalone amidst ? here's a link to their release page: https://github.com/toolbox4minecraft/amidst/releases/tag/v4.3-beta2

**Comment by scottosx** [comment]
Glad you like the review. Feel free to share it anyway you like.

The map icons are weird for me. I have seen them work before in Amidst for Forge. They definitely work in regular Amidst and always have. I will try to see if certain mods or plugins cause it and report back.

**Comment by scottosx** [comment]
Clicking the icons works for me now or at least I haven't been able to find the condition that made it stop working. Something did though as the video documents it. I don't think it is anything for you to worry about however.

If I can track it down then I will post it as a new issue.
