### ISSUE TITLE
Support for CUSTOMIZED world-type

### ISSUE THREAD

**Issue by vico93** [fraenkelc/amidst-forge#6]
Hi! Is possible to amidst-forge have support for Customized (and presets)?

Since this is a [vanilla world-type](https://minecraft.gamepedia.com/Customized) i requested [first on original amidst repo](https://github.com/toolbox4minecraft/amidst/issues/380), but since i didnt get any response from both the original author or fork authors i came here to ask too.

Thanks in advance!

**Comment by fraenkelc** [comment]
I realize this is probably not what you want, but you can already open customized and superflat worlds in amidst for forge using the Amidst Overworld button after creating and joining those worlds.

I do not intend to add support for customized / superflat worlds to amidst itsself. That is out of scope for both this mod and the amidst fork I'm maintaining for use with this mod.

**Comment by vico93** [comment]
Well i tried "Amidst Overworld" but no matter what seed i enter the same terrain is rendered.

**Comment by fraenkelc** [comment]
yes, it renders the seed you created the world with (that what that button does)

**Comment by vico93** [comment]
Ah, i thought i could launch Amidst via Overworld and then generate seeds from similar presets. So it's redundant for my case, because I'd like to preview the world to see if it's worth it or not **before** create it.

Still thanks for the attention!
