### ISSUE TITLE
How to view other dimensions? 

### ISSUE THREAD

**Issue by ghost** [fraenkelc/amidst-forge#7]
Dimension switching does not work.
I see Amidst Overworld button even if i'm in another dimension, and when I press it just opens Amidst (does not switches dimension) (Tried Nether and Aether 2 Highlands). I can see Aether biomes in list, but the map shows Overworld, regardless in which dimension I'm in the game.
P.S.: Its not Aether legacy, its Highlands

**Comment by fraenkelc** [comment]
It current is not possible to view other dimensions than the overworld in amidst for forge.
The support in for other dimensions in Amidst is quite limited - from what I remember the nether only simulates structure generation and the end is implemented entirely in the Amidst code and does not call into the minecraft classes.
Supporting multiple dimensions properly would require a number of extensions to Amidst which I currently do not want to a) implement and b) support on my fork of amidst.

**Comment by ghost** [comment]
Ok, thank you for answer. I have an idea, perhaps dimension support could added by simply redirecting a dimension in which I'm in as overworld dimension for Amidst? So Amidst will think that it works with overworld, but actually it will show other dimension. In other words to make Amidst think that its working with another world type (like in case with Biomes o Plenty).
(Sorry for my English)

**Comment by fraenkelc** [comment]
Oh, I'm sure there are lots of hacky ways to solve this. 
I might take a look at implementing a command to that works similar to overworld, but with a customizable dimension id. No guarantees on that though.

**Comment by fraenkelc** [comment]
I'm closing this issue for now as I'm not getting around to doing it in the near future.
