### ISSUE TITLE
[Suggestion] Add a Chunk Grid Layer

### ISSUE THREAD

**Issue by lrwerewolf** [fraenkelc/amidst-forge#8]
I've not been able to find a setting for this yet.  The existing grid is dynamic and changes based on zoom level, and I've not been able to zoom in far enough that it becomes chunk sized.

A specific example -- I am looking for an area of desert or desert derivative 9x9 chunks in size.  Using the slime chunk layer helps a little with trying to figure out scale and grid, but an actual chunk-based grid would be delightful.

User Story:
As a player looking for specific configurations of biomes and chunks,
I would like to be able to apply a layer that shows the chunk grid,
So that I can better see the arrangement of biomes vs. chunks.

**Comment by fraenkelc** [comment]
Please raise this issue upstream (https://github.com/toolbox4minecraft/amidst) - amidst for forge only deals with the integration of modded worldgen.
