### ISSUE TITLE
I am having the OTG black screen issue with Amidst 0.6.0 with the following mods installed:

### ISSUE THREAD

**Issue by fraenkelc** [fraenkelc/amidst-forge#9]
I am having the OTG black screen issue with Amidst 0.6.0 with the following mods installed:
OpenTerrainGenerator-1.12.2 - v6.jar
OTG-Skylands-1.12.2-v5.jar
amidst-forge-1.12.2-0.6.0.jar

Skylands is a preset for OTG that has ~60 biomes, so should be well below the 256 biome limit. I am launching a Skylands world and using Amidst Overworld, then choosing "New from random seed" and selecting the "default" world type (only vanilla world types are available - I assume this is normal?) After this, I get the black screen with "unknown" biomes. Also tried with the Flatlands preset. 

Edit: The first issue was apparently that the Biome IDs of the preset were above 256. However, setting them to below 256 (and avoiding vanilla assigned values) results in that continuous stream of blank error windows.

_Originally posted by @Alaisx in https://github.com/fraenkelc/amidst-forge/issues/4#issuecomment-485177891_

**Comment by fraenkelc** [comment]
@Alaisx can you post your modified configuration so I can try to reproduce the issue?

**Comment by Alaisx** [comment]
[Skylands-Modified.zip](https://github.com/fraenkelc/amidst-forge/files/3101291/Skylands-Modified.zip)

**Comment by fraenkelc** [comment]
Turns out OTG is hacking the Forge Biome registry and is missing some spots where it should add its biomes too. I've added a workaround for this particular spot and I can now at least open worlds using your modified skylands config. The fix will be in 0.6.1.

**Comment by Alaisx** [comment]
Awesome. Thanks for the swift response.
